name: web_devop
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # hive no sql database
  hive: ^2.2.3
  # path
  path_provider: ^2.1.1
  # get it singleton
  get_it: ^7.6.4
  # equatable
  equatable: ^2.0.5
  # bloc state manager
  flutter_bloc: ^8.1.3
  # async
  async: ^2.11.0
  # forms
  formz: ^0.6.0
  # internet check
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  # interceptor
  dio: ^5.3.2
  dio_retry_plus: ^2.0.0
  # alice = chuck
  chuck_interceptor: ^2.0.2
  # device_info_plus:
  device_info_plus: ^9.0.3
  # box
  gap: ^3.0.1
  # pin put:
  pinput: ^3.0.1
  # svg render
  flutter_svg: ^2.0.7
  # syncfusion chart
  syncfusion_flutter_charts: ^22.2.11
  # syncfusion dataPicker
  syncfusion_flutter_datepicker: ^22.2.11
  # video player
  video_player: ^2.7.1
  # cached image
  cached_network_image: ^3.2.3
  # native splash
  flutter_native_splash: ^2.3.2
  # firebase
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_messaging: ^14.6.7
  firebase_crashlytics: ^3.3.5
  firebase_performance: ^0.9.2+5
  # local notification
  flutter_local_notifications: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
