// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYh1UAbKlB4IJie1vLgfSCP3CdN6_A3pc',
    appId: '1:48469773885:web:02ae39e5569af9e87ca454',
    messagingSenderId: '48469773885',
    projectId: 'olloyorcom-d6869',
    authDomain: 'olloyorcom-d6869.firebaseapp.com',
    storageBucket: 'olloyorcom-d6869.firebasestorage.app',
    measurementId: 'G-1SZXW31Y65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4qfVBURGmNDnQYJS_J_dvL8oJwz4Ii1U',
    appId: '1:48469773885:android:5cbcd8dee47a56ba7ca454',
    messagingSenderId: '48469773885',
    projectId: 'olloyorcom-d6869',
    storageBucket: 'olloyorcom-d6869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRrKpB8IhsSdNdf1H2DLNIEsCH4w79Eg',
    appId: '1:48469773885:ios:2f99f5b6c3e54ea17ca454',
    messagingSenderId: '48469773885',
    projectId: 'olloyorcom-d6869',
    storageBucket: 'olloyorcom-d6869.firebasestorage.app',
    iosBundleId: 'com.example.webDevop',
  );
}
